apiVersion: v1
kind: Pod
metadata:
  name: sca-eureka
  labels: 
    app: sca-eureka
spec:
  containers:
    - name: sca-eureka
      image: breno500as/sca-eureka-service:123
      ports:
       - containerPort: 8761